Sign up
ArtyomPurenok/tms_blog pull request #4
Opened 2022-04-27 21:23 UTC by ArtyomPurenok

Обратите пожалуйста внимания на структуру, вот так должно быть в дальнейшем?

2022-05-02 14:40 UTC, ArtyomPurenok commented
Посмотрите пожалуйста файл  /[src]/[Components]/[Input]/InputForSignUp.tsx там всё собственно и так понятно будет. Это я с вопросом по функциям.

2022-05-04 07:15 UTC, JohnyNiks requested changes

2022-05-04 07:15 UTC, JohnyNiks commented on src/App.tsx
> +     <MainJSX/>
Если это компонент страницы регистрации, то и называться он должен соответствующее. 
Например SignUpPage

2022-05-04 07:15 UTC, JohnyNiks commented on src/Components/Input/InputForSignUp.tsx
> +export const InputForSignUp = ({EmailVerification, LoginVerification, PasswordInputOne, PasswordInputTwo, BorderColorUserInput, SignUpInpClass, SignUpInputType, SignUpTxtNameForInput, SignUpInputPlac
Сами функции должны иметь одно название чтобы пробрасывать их не через знак ||.

2022-05-04 07:15 UTC, JohnyNiks commented on src/Components/Input/InputForSignUp.tsx
> +        <input onChange={EmailVerification || LoginVerification || PasswordInputOne || PasswordInputTwo}    className={SignUpInpClass} style={{borderColor: BorderColorEmailInput || BorderColorUserInp
```suggestion
        <input onChange={onChange}  className={SignUpInpClass} style={{borderColor: BorderColorEmailInput || BorderColorUserInput || BorderColorInputPasswords}} type={SignUpInputType} placeholder={SignUpInputPlaceholder}/>
```

2022-05-04 07:15 UTC, JohnyNiks commented on src/BoxWithInputs/BoxWithInputs.tsx
> +        LoginVerification = {loginVerification}
```suggestion
        onChange={loginVerification}
```

2022-05-04 07:16 UTC, JohnyNiks commented
Все компоненты должны находится в папке components

2022-05-11 21:43 UTC, closed without merging